Flowpack:
  ElasticSearch:
    clients:
      default:
        -
          host: localhost
          port: 9200
          username: ''
          password: ''
    realtimeIndexing:
      enabled: true
      client: default
    transfer:
      connectionTimeout: 60
